### ISSUE TITLE
Enable Log Aggregation for OPA

### ISSUE THREAD

**Issue by maltesander** [stackabletech/opa-operator#410]
See https://github.com/stackabletech/hbase-operator/issues/291 and https://github.com/stackabletech/docker-images/pull/283 for reference.

This is part of https://github.com/stackabletech/issues/issues/288

Related: https://github.com/stackabletech/opa-operator/issues/373

## TODO

- [x] https://github.com/stackabletech/docker-images/pull/329
- [x] https://github.com/stackabletech/docker-images/pull/333
- [x] https://github.com/stackabletech/opa-operator/pull/411
- [x] https://github.com/stackabletech/operator-rs/pull/557
- [x] https://github.com/stackabletech/opa-operator/pull/420
