### ISSUE TITLE
First release of userinfo fecher tool (with Keycloak backend)

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/opa-operator#477]
# Description

The Stackable Data Plattform should integrate with identity providers to allow authorizing access based on arbitrary user attributes from those providers. The most common attributes will probably be groups and roles a user has, but other use cases are certain to come up, so this should be able to retrieve  user configurable attributes as well.

## Development
The current idea is to develop the userinfofetcher as a module in the opa operator [https://github.com/stackabletech/opa-operator](https://github.com/stackabletech/opa-operator), to avoid additional build complexity by spinning this out into a project of its own.
If need be, it can still be moved out of the repo at a later date.

PoC code for this functionality is available in this branch: https://github.com/stackabletech/opa-operator/tree/spike/user-info-fetcher

## Functionality
For an initial release the following items must be achieved:

```[tasklist]
### Must Have
- [ ] https://github.com/stackabletech/opa-operator/issues/509
- [x] Investigate customer issue
- [ ] https://github.com/stackabletech/opa-operator/issues/478
- [x] Discussion about what else is needed for release in 24.3
- [x] Functionality to retrieve user attributes from Keycloak
- [x] Cache requests for users information with configurable cache eviction time
- [x] UserInfoFetcher has to be configurable via CRD (can be the opa crd if that makes sense)
- [x] Retrieving arbitrary user properties has to be implemented
- [x] Design has to be modular, so that other backend than Keycloak can be added at a later time
- [x] The fetcher gets asked: "Which groups is the user sub (random stable identifier in KeyclaoK) part of?"
- [x] The fetcher also can be asked: "Which groups is the username part of?"
- [x] Documentation - usage guide
- [ ] https://github.com/stackabletech/opa-operator/issues/517
```

## ADR
Some issues to be covered in the ADR:

- Caching
- Centralized component to minimize components that talk to AD/etc.

## CRD Design

Configuration of the userinfofetcher will be done inside of the existing Opa crd.

### Option 1

```yaml
---
apiVersion: opa.stackable.tech/v1alpha1
kind: OpaCluster
metadata:
  name: simple-opa
spec:
  clusterConfig:
    userInfoProvider:
      keycloak:
         url: http://iaeiaeiea:5678 # maybe pull this out into a configmap?
         credentialsSecret:
         tls: TlsConfig
         cache:
            maxEntries: ...  # all the cache settings are to be understood as placeholders
            ttl: ...
            evictionStrategy: ..
         extraAttributes:
            stackableField1: remoteField1
  image:
    productVersion: "0.51.0"
    stackableVersion: "23.7.0"
  servers:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
```

### Option 2

@sbernauer : have some decouplign and say its too complicated

## Deployment
Currently the proposed deployment is for the UserInfoFetcher to run as a sidecar container in the opa pods. This would allow the userinfofetcher to only listen on the loopback interface and not be available from outside of the pod. 
For this reason it should be possible to not run tls for the userinfofetcher, as the pod would need to be breached to compromise it - and at that point in time an attacker would have access to the certificate and key that can be used to authenticate as well.

![image](https://github.com/stackabletech/opa-operator/assets/1070361/db44db1d-697e-4109-b73e-64c5d6650df7)

For the first iteration it is agreed to go with the deployment model shown in the diagram above.

At later stages we may want to look into adding a central userinfofetcher as caching layer to avoid ddos-ing identity providers.

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 

```[tasklist]
### Author
- [ ] Changes are OpenShift compatible
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
```

```[tasklist]
### Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
### Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

**Comment by lfrancke** [comment]
Reopening for https://github.com/stackabletech/opa-operator/issues/517

**Comment by sbernauer** [comment]
I think I personally would make a new Issue to change the common `tls` struct to default to webPki (or similar) across all CRDs. But I leave it to you ;)

**Comment by lfrancke** [comment]
That is to be refined.
If you're interested let us know
https://stackable-workspace.slack.com/archives/C06GWEEG602/p1707484224033069

**Comment by sbernauer** [comment]
I'm happy to let others refine, just tried to prevent this from some form of feature creeping :sweat_smile:
