### ISSUE TITLE
Support Openldap backend for user-info-fetcher

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/opa-operator#523]
## Description

As a user of the opa-operator, I want the user-info-fetcher component to support OpenLDAP as a backend for fetching user information.

## Value

Supporting OpenLDAP will allow organizations that use OpenLDAP for directory services to integrate seamlessly with the user-info-fetcher component, improving compatibility and easing adoption of the opa-operator in environments using OpenLDAP.

## Tasks
- [x] Implement OpenLDAP support in the user-info-fetcher
- [x] CRD change decision: https://github.com/stackabletech/decisions/issues/65
- [x] Document the configuration and usage of OpenLDAP with the user-info-fetcher
- [x] Add an integration test to verify OpenLDAP backend functionality

## Acceptance Criteria

- [x] Documentation is updated to explain how to configure OpenLDAP backend
- [x] Tests demonstrate that user-info-fetcher works correctly with OpenLDAP backend

**Comment by dervoeti** [comment]
Docs: https://docs.stackable.tech/home/nightly/opa/usage-guide/user-info-fetcher/#backend-openldap

## Release Note

The User info fetcher now has experimental support for OpenLDAP as backend.
See the documentation of the User info fetcher for details on how to configure it: https://docs.stackable.tech/home/nightly/opa/usage-guide/user-info-fetcher/#backend-openldap
