### ISSUE TITLE
Switch all examples, demos and integration tests to use the rego rules wrapper for UIF

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/opa-operator#617]
Part of https://github.com/stackabletech/issues/issues/499

Remove regorule http calls and replace them with the regorules from https://github.com/stackabletech/opa-operator/pull/580

```[tasklist]
### Tasks
- [x] opa-operator - already updated
- [x] hdfs-operator - uif not used
- [ ] https://github.com/stackabletech/trino-operator/pull/635
- [ ] https://github.com/stackabletech/demos/pull/91
```

**Comment by sbernauer** [comment]
All usages should be updated :)
